sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=rso26/ride-catalogue:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: jz3JAMqzYC7V8Mh6naqC5SNiJUHei1cOa/5kpCqrZAfcc6LajA8QyNB9ITgcl2dQ6J6d7I9MPUpEGYALS7cLhCPWLQkIOnfJgql7YfXkJ6uhIG/KQVqyjVWzkQ320+ulftzwGM4OBBk8tlUu4WLuLlWhrGGwd933Wdj7+of44DAETE8eaqA3L4hAQNHh5plvQP6i6+SKEl1BaMeovI6IoX0jYk3X8xn1ebxyqtgj7fAuZB/IR6PMp7lgfed115F+OGVrJQn3qx0n6OPX9Q1U5yjKAGM/XflKShSeKyvocMqKLIt9N3cyCS52Nju0TLSoI+8AapmxjxKGVcaqgz+0f0bUBxOGI5T1yrSKKce6PG6SpZtkZd/YjVhfSQxF9rv1kxfsTkyJFuIviFJl+/W5MoyNput5mhk+NRnE0UpB1neTtZtwcz/KCTfcRdBo3e4/hPlvu1WSCcGx5gMt3sm3LHOejLYJz10AzpPfeL/97tuzWU/BEaP2v7g42JzYVwhs5TribjHOVuP1Y3yWCfDtKo3ht3TjRhGLPOJsAeoMKOqcpDL6cDADebXF8/xkwdDe19rABPEFFKvwLxNVscuMLOc9K22XgD9ywtuMBYx2fPnxxvUMch/KD2w3322I4mjM3dsDPEO92xk6ASdgg1oa8YelAVkee/QLbVKnDzuzYAQ=
  - secure: GexoZqB+/Hpm/19VZ4T0BQJtriFSzUF89/PtRjVRLx07Co5/AzOiH+DlRVG4Hf1dCM6KEdeEKlwjJIW6Hj3orfcwTVNXO6XPKIwU/H6idyUB3wuhlhLofOawRwezHqrXccKLMz9/OurodmyFeZ+0Bd0kbDGc5RMQnGXYi6gzOZ/K4URFAoNlBzHvjBaFYljVQos1kuS5TVN4CVIDnsRpcU11AJBsm3yUdovsN5a9BzZWI2U8d7WbfPyH6fbHO1x1S6f4v/oP8TpeuKCZgzKlEqx+pANVUi19QbZm0snNigsa/3mYYsR6KKZjBwX35QnLqrTIao3uuAOtmFdKnB6l4kdYDQTW8YVNhLx7DX7iMkRBQTladVK/d0tScKlL+zQpZOKIYM44ymYAWFoCoH0Fam39U0y/+DhKFdIJ0rLWPuW2IC+rl9syn5D54TYRNH1JY7VLMFNLS3a9u2GlXDig5CZcsdXr+S/dwpt+kaU5IUc0+ku24iohJaPCLreZ/EQzF2mJS5UArqHSOW8XSUsmIyu1pjgr7ShcQAz5lDn+9EiMFjym896V8EP49fRxdhb7uTSSSR5EFIX0uz0ASXBQdxVY8p2Ru6othQFUmnEZyq1OrrG4lQNOeCUokQhvIK/Zs1nZcoC9c5w5mxP3GA8HTU7e/FpWA4kYVwmyN9dT+5Y=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"